version: 2

references:
  save_node_modules: &save_node_modules
    save_cache:
      paths:
        - node_modules
      key: v1-dependencies-{{ checksum "yarn.lock" }}
  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "yarn.lock" }}
        - v1-dependencies-

workflows:
  version: 2
  all-check:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - test:
          requires:
            - lint
      - e2e:
          requires:
            - lint

jobs:
  lint:
    docker:
      - image: circleci/node:12.13-stretch-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - *restore_node_modules
      - run: yarn install
      - *save_node_modules
      - run: yarn lint
  build:
    docker:
      - image: circleci/node:12.13-stretch-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - *restore_node_modules
      - run: yarn install
      - *save_node_modules
      - run: yarn build
  test:
    docker:
      - image: circleci/node:12.13-stretch-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - *restore_node_modules
      - run: yarn install
      - *save_node_modules
      - run: yarn test
  e2e:
    docker:
      - image: circleci/node:12.13-stretch-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - *restore_node_modules
      - run: yarn install
      - *save_node_modules
      - run: yarn e2e
