name: Check Renovate Config

on:
  push:
    paths:
      - 'renovate.json'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: npm
      - name: Validate Renovate config
        run: npx --package renovate -c 'renovate-config-validator'
